//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class AssingedCourse
    {
        [DisplayName("Course ID")]
        public int ACourses_id { get; set; }
        [DisplayName("Course Name")]
        public string Acourse_name { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> Teacher { get; set; }
        public Nullable<int> Student { get; set; }
    
        public virtual Course Course1 { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
