//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Staff
    {
        [DisplayName("Staff ID")]
        public int staff_id { get; set; }
        [DisplayName("Staff Pass")]
        public string staff_pass { get; set; }
        [DisplayName("Staff Name")]
        public string staff_name { get; set; }
        [DisplayName("Staff Salary")]
        public Nullable<decimal> staff_salary { get; set; }
        [DisplayName("Staff Duty")]
        public string staff_dty { get; set; }
        [DisplayName("Department")]
        public Nullable<int> staff_depart { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
