//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AssingedCourses = new HashSet<AssingedCourse>();
            this.TransDetails = new HashSet<TransDetail>();
        }

        [DisplayName("Student ID")]
        public int S_id { get; set; }
        [DisplayName("Student Pass")]
        public string S_pass { get; set; }
        [DisplayName("Student Name")]
        public string S_name { get; set; }
        [DisplayName("Student Fees")]
        public Nullable<decimal> S_fees { get; set; }
        [DisplayName("CGPA")]
        public Nullable<double> S_cgpa { get; set; }
        [DisplayName("Semester")]
        public Nullable<int> S_semester { get; set; }
        [DisplayName("Degree")]
        public string S_major { get; set; }
        [DisplayName("Department")]
        public Nullable<int> S_depart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssingedCourse> AssingedCourses { get; set; }
        public virtual Department Department { get; set; }
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransDetail> TransDetails { get; set; }
    }
}
