//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.AssingedCourses = new HashSet<AssingedCourse>();
        }

        [DisplayName("Teacher ID")]
        public int T_id { get; set; }
        [DisplayName("Teacher Pass")]
        public string T_pass { get; set; }
        [DisplayName("Teacher Name")]
        public string T_name { get; set; }
        [DisplayName("Teacher Salary")]
        public Nullable<decimal> T_salary { get; set; }
        [DisplayName("Deparment")]
        public Nullable<int> T_Depart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssingedCourse> AssingedCourses { get; set; }
        public virtual Department Department { get; set; }
    }
}
