//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TransDetail
    {
        [DisplayName("Transaction ID")]
        public int trans_id { get; set; }
        [DisplayName("Transation Details")]
        public string trans_details { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<int> Student { get; set; }
    
        public virtual Student Student1 { get; set; }
    }
}
